steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/artportable-web/artportable-backend:$COMMIT_SHA",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/artportable-web/artportable-backend:$COMMIT_SHA",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
        "run",
        "deploy",
        "artportable-backend",
        "--image",
        "europe-north1-docker.pkg.dev/$PROJECT_ID/artportable-web/artportable-backend:$COMMIT_SHA",
        "--region",
        "europe-north1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--memory",
        "1Gi",
        "--set-env-vars",
        "ENVIRONMENT=Production",
        "--set-secrets",
        "ConnectionStrings__DefaultConnection=projects/$PROJECT_ID/secrets/DefaultConnection:latest",
        "--vpc-connector",
        "cloud-run-connector",
        "--egress",
        "all",
      ]
options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "europe-north1-docker.pkg.dev/$PROJECT_ID/artportable-web/artportable-backend:$COMMIT_SHA"
